### ISSUE TITLE
SCR_CharacterHitZone script failing

### ISSUE THREAD

**Issue by Khaeltan** [Revive-System/StayAlive#1]
Hey there!
Just wanted to let you know that your script modding SCR_CHaracterHitZone is failing because the inheritance class changed from ScriptedHitZone to SCR_HitZone!

Hope this helps!

**Comment by Kexanone** [comment]
Resolved in [ac32708](https://github.com/Revive-System/StayAlive/commit/ac32708abe99ed5429e703c9583f154fd9797203)
